whiteboard_app/plugins/whiteboard_web/config/routes.rb
Rails.application.routes.draw do
  resources :whiteboards
end

whiteboard_app/plugins/whiteboard_web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

whiteboard_app/plugins/whiteboard_web/app/controllers/whiteboards_controller.rb
class WhiteboardsController < ApplicationController
    def create
        create_whiteboard(
            name: params.require(:name),
            gui: self,
            repo: Rails.configuration.whiteboard_repo
        )
    end

    def whiteboard_created(id)
        render plain: id
    end

    def validation_failed(errors)
        @errors = errors
        render "validation_failed"
    end
end

whiteboard_app/plugins/whiteboard_web/app/helpers/application_helper.rb
module ApplicationHelper
end

whiteboard_app/plugins/whiteboard_web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhiteboardWeb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

whiteboard_app/plugins/whiteboard_web/app/views/whiteboards/_error.html.slim
li=t("validations.#{error[:validation]}", field: error[:field])

whiteboard_app/plugins/whiteboard_web/app/views/whiteboards/_form.html.slim
= form_tag whiteboards_path do
  = label_tag :name
  = text_field_tag :name, params[:name]

  br

= submit_tag

whiteboard_app/plugins/whiteboard_web/app/views/whiteboards/new.html.slim
= render "form"

whiteboard_app/plugins/whiteboard_web/app/views/whiteboards/validation_failed.html.slim
ul
  = render partial: "error", collection: @errors

= render "form"